version: '3.8'

services:
  web:
    build:
      context: ./nginx
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./env/php.env
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    env_file:
      - ./env/pma.env
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - ./env/db.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: